### ISSUE TITLE
Error: const PassThrough = require('stream').PassThrough; 

### ISSUE THREAD

**Issue by leotaglia** [shivasiddharth/Stremio-RaspberryPi#27]
Hi, I'm getting the below error after installing.

pi@raspberrypi:/etc/apt $ /home/${USER}/Stremio-RaspberryPi/src/server-launcher.sh

/home/pi/Stremio-RaspberryPi/stremio-shell/server.js:40095
const PassThrough = require('stream').PassThrough;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
pi@raspberrypi:/etc/apt $

Any idea how to fix it?

**Comment by leotaglia** [comment]
Nevermind, I had an old node version. Updating it solved the error.
