### ISSUE TITLE
HTTPS failure and more

### ISSUE THREAD

**Issue by vliapis** [shivasiddharth/Stremio-RaspberryPi#39]
Hello again!

The reason i'm posting again was brought up while trying to turn the "desktop" Stremio into a "stremio streaming server", which it failed.

The main error displayed is "http or SSL error".

A few more detailed info now:

starting Stremio from console as "pi" user, i get the following errors (mind you, i can localy watch streams just fine):
"HTTPS request certificate failed" on the Stremio GUI and,

`WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.`

```
js: HTTPS error
{ Error: listen EADDRINUSE: address already in use :::11470
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.require.727../cache (/opt/stremio/server.js:135065:8)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 11470 }
{ Error: listen EADDRINUSE: address already in use :::12470
    at Server.setupListenHandle [as _listen2] (net.js:1280:14)
    at listenInCluster (net.js:1328:12)
    at Server.listen (net.js:1415:7)
    at Object.require.727../cache (/opt/stremio/server.js:135087:9)
    at s (/opt/stremio/server.js:1:338)
    at e (/opt/stremio/server.js:1:509)
    at Object.<anonymous> (/opt/stremio/server.js:1:527)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 12470 }
EngineFS server started at http://127.0.0.1:11471


```
I get the previous error, two times in a row.

Then, when i enable "Enable remote HTTPS connections" i get:

"HTTPS request certificate failed" on the Stremio GUI and,
```
EngineFS server started at http://127.0.0.1:11471

-> GET /get-https?authKey=kejlUtklniRMgyWZBI04ntLmusHK_3bMpl0gNbDvwkA%3D&ipAddress=192.168.10.50 
Cannot get valid certificate TypeError: Cannot read property 'port' of null
    at /opt/stremio/server.js:135027:34
js: HTTPS error
```

on the console i get:

```
-> OPTIONS /settings 
-> POST /settings 
-> GET /get-https?authKey=kejlUtklniRMgyWZBI04ntLmusHK_3bMpl0gNbDvwkA%3D&ipAddress=192.168.10.50 
Cannot get valid certificate TypeError: Cannot read property 'port' of null
    at /opt/stremio/server.js:135027:34
js: HTTPS error
Resizing cache size to 2048MB from 608MB by deleting 0 files
```

For starters, how many ports stremio keeps open. I see that even though i kill stremio on exit (the taskbar icon with the exit option never works sadly), one port, usualy 11470 stays open. The program that uses that port is "node" (node.js i guess).

Any help is appreciated!

**Comment by shivasiddharth** [comment]
1. Start Stremio from the menu bar and not from terminal (not sure if it makes any difference).
2. What URL are you using for remote access (as far as i know, there is no issue with remote access)?
