### ISSUE TITLE
Age old issue: Streaming to another device

### ISSUE THREAD

**Issue by vliapis** [shivasiddharth/Stremio-RaspberryPi#45]
Hi, I posted again and got nowhere closer to a solution. I got a new error this time though, might be helpful in order to provide a solution:

```
Stremio streaming server has thrown an error 
QProcess::ProcessError code: 1

/opt/stremio/server.js:134964
	var body = JSON.stringify({ error: error, result: result });
	                ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at /opt/stremio/server.js:134964:18
    at /opt/stremio/server.js:140589:21
    at /opt/stremio/server.js:135257:25
    at ClientRequest.simpleGet (/opt/stremio/server.js:125490:21)
    at ClientRequest.f (/opt/stremio/server.js:106176:25)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:448:20)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at TLSSocket.emit (events.js:198:13)
    at TLSSocket.EventEmitter.emit (domain.js:448:20)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
That happened when i tried to start a stream from my phone after having connected to https://address:12470

Enable Remote HTTPS connection is active.

Thanx in advance!

**Comment by LiamRiddell** [comment]
You should be able to do this using `stremio-server` and I use Raspberry PI 5. See https://github.com/shivasiddharth/Stremio-RaspberryPi/issues/47#issuecomment-1947036524
